If (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {   
  $arguments = "& '" + $MyInvocation.MyCommand.Definition + "'"
  Start-Process powershell -Verb runAs -ArgumentList $arguments
  Break
}

$hosts_path = "C:\Windows\System32\Drivers\etc\hosts"
$generated_path = Resolve-Path ((Split-Path -Parent $PSCommandPath) + "/../build/pc.hosts")
$header = "# Auto Generated by luma-hosts-blocklist"

$content = Get-Content $hosts_path
$base = @()
foreach($line in $content) {
  if($line -eq $header) {
    Break
  }
  $base += $line
}

$base += $header
$base += Get-Content $generated_path

Write-Output $base | Out-File -Encoding utf8 $hosts_path
